//login
export const FETCH_LOGIN_RESULT = 'FETCH_LOGIN_RESULT';
export const RECEIVE_LOGIN_RESULT = 'RECEIVE_LOGIN_RESULT';
export const CHANGE_LOGIN_AUTH = 'CHANGE_LOGIN_AUTH';

//timeConsuming
export const START_HANDLE_TIME_CONSUMING = 'START_HANDLE_TIME_CONSUMING';
export const STOP_HANDLE_TIME_CONSUMING = 'STOP_HANDLE_TIME_CONSUMING';

//nav
export const NAVIGATION = 'NAVIGATION';
export const NAVIGATION_MAIN = 'NAVIGATION_MAIN';

export const FETCH_LOADING = 'FETCH_LOADING';

export const FETCH_FINANCE_DATA = 'FETCH_FINANCE_DATA';
export const UPDATE_FINANCE_DATA = 'UPDATE_FINANCE_DATA';

export const DECREMENT = 'DECREMENT';